first_name = input()
last_name = input()
birthday = input()
print("#############################")
print("#  _  _ ___ _    _    ___   #")
print("# | || | __| |  | |  / _ \\  #")
print("# | __ | _|| |__| |_| (_) | #")
print("# |_||_|___|____|____\\___/  #")
print("#############################")
print("=============================")
print("My name is"+"\t",first_name,last_name)
print("My birthday is",birthday)
print("You can call me",first_name)
print("=============================")